name: 'Automatically build the XNU kernel'

on:
  release:
    types: [published]

jobs:
  build-kernel:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build XNU
        run: bash build_under_osx.sh