name: 'Automatically build the XNU kernel'

on:
  push:
    branches:
      - 'main'
  release:
    types: [published]

jobs:
  build-kernel:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build XNU
        run: bash build_xnu.sh
      - name: Upload raw kernel (no KC)
        uses: actions/upload-artifact@v3
        with:
          name: kernel.development
          path: xnu/BUILD/obj/kernel.development